<?php
return array (
  'cache_lifetime_channel' => '30',
  'cache_lifetime_index' => '10',
  'cache_lifetime_view' => '72',
  'default_theme' => 'default',
  'rewrite_channel' => 'list',
  'rewrite_suffix' => 'html',
  'rewrite_view' => 'view',
  'web_beian' => '',
  'web_caching' => '0',
  'web_close' => '0',
  'web_closecon' => '',
  'web_debug' => '0',
  'web_description' => '',
  'web_gzip_open' => '1',
  'web_keywords' => '',
  'web_name' => '我的网站',
  'web_path_depr' => '-',
  'web_path_suffix' => 'html',
  'web_robot_onnotes' => '1',
  'web_seo_name' => '自豪的使用txtcms',
  'web_tongji' => '',
  'web_url' => 'http://txtcms.cm/',
  'web_url_model' => '1',
  'web_url_rewrite' => '0',
);
?>